name: Deploy to Production VPS & Build Production Images

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy repository to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          rm: true
          source: "."
          target: "/${{ secrets.SSH_USERNAME }}/portfolio-v5"

      - name: Execute remote SSH deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /${{ secrets.SSH_USERNAME }}/portfolio-v5
            cp /${{ secrets.SSH_USERNAME }}/.env /${{ secrets.SSH_USERNAME }}/portfolio-v5/.env
            bash /${{ secrets.SSH_USERNAME }}/portfolio-v5/deploy.sh
